import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]

decorations = "Buttonless"

opacity = 0.85
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14
